language: generic
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
git:
  depth: false
services:
  - docker
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT=codattle
    - CLUSTER=codattle-kubernetes
    - ZONE=europe-west2-a
before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl
deploy:
  provider: script
  script: chmod +x deployment/gcr/build-containers.sh && deployment/gcr/build-containers.sh
  skip_cleanup: true
  on:
    branch: master