version: '3'
services:
  rabbitmq:
    build: ../docker/rabbitmq
    ports:
    - "5672:5672"
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq
  mongodb:
    build: ../docker/mongodb
    ports:
    - "27017:27017"
    volumes:
    - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
  storage:
    image: halverneus/static-file-server
    ports:
    - "8081:8080"
    volumes:
    - ./storage:/web
  keycloak:
    image: jboss/keycloak
    ports:
    - "8090:8080"
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm.json
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: H2
      KEYCLOAK_IMPORT: /tmp/realm.json
volumes:
  rabbitmq_data: {}
  mongodb_data: {}