apiVersion: v1
kind: Service
metadata:
  name: codattle-core
  labels:
    app.kubernetes.io/name: codattle-core
    helm.sh/chart: {{ include "codattle.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: codattle-core
    app.kubernetes.io/instance: {{ .Release.Name }}
