apiVersion: apps/v1
kind: Deployment
metadata:
  name: codattle-simulation
  labels:
    app.kubernetes.io/name: codattle-simulation
    helm.sh/chart: {{ include "codattle.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: codattle-simulation
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: codattle-simulation
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: codattle-simulation
          image: {{ .Values.repository }}/codattle-simulation:{{ .Values.images.simulation.tag }}
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          env:
            - name: QUEUE_URL
              value: "amqp://codattle-rabbitmq"
            - name: GRAPHQL_URL
              value: "http://codattle-core:80/graphql"
