apiVersion: v1
kind: Service
metadata:
  name: codattle-simulation
  labels:
    app.kubernetes.io/name: codattle-simulation
    helm.sh/chart: {{ include "codattle.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: codattle-simulation
    app.kubernetes.io/instance: {{ .Release.Name }}
