// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");
var GameList$ReactTemplate = require("./page/GameList.bs.js");
var HomePage$ReactTemplate = require("./page/HomePage.bs.js");
var Dashboard$ReactTemplate = require("./page/Dashboard.bs.js");
var MatchList$ReactTemplate = require("./page/MatchList.bs.js");
var GameWizard$ReactTemplate = require("./page/GameWizard.bs.js");
var GameDetails$ReactTemplate = require("./page/GameDetails.bs.js");
var MatchWizard$ReactTemplate = require("./page/MatchWizard.bs.js");
var UserProfile$ReactTemplate = require("./page/UserProfile.bs.js");
var MatchDetails$ReactTemplate = require("./page/MatchDetails.bs.js");
var NotFoundPage$ReactTemplate = require("./page/NotFoundPage.bs.js");
var ScriptWizard$ReactTemplate = require("./page/ScriptWizard.bs.js");
var NavigationBar$ReactTemplate = require("./page/NavigationBar.bs.js");

function App(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url[/* path */0];
  var page;
  var exit = 0;
  if (match) {
    switch (match[0]) {
      case "dashboard" : 
          if (match[1]) {
            exit = 1;
          } else {
            page = React.createElement(Dashboard$ReactTemplate.make, { });
          }
          break;
      case "games" : 
          var match$1 = match[1];
          if (match$1) {
            var gameId = match$1[0];
            var exit$1 = 0;
            var match$2 = match$1[1];
            if (match$2) {
              switch (match$2[0]) {
                case "matches" : 
                    if (match$2[1]) {
                      exit$1 = 2;
                    } else {
                      page = React.createElement(MatchList$ReactTemplate.make, {
                            gameId: gameId
                          });
                    }
                    break;
                case "new-match" : 
                    if (match$2[1]) {
                      exit$1 = 2;
                    } else {
                      page = React.createElement(MatchWizard$ReactTemplate.make, {
                            gameId: gameId
                          });
                    }
                    break;
                default:
                  exit$1 = 2;
              }
            } else {
              page = React.createElement(GameDetails$ReactTemplate.make, {
                    gameId: gameId
                  });
            }
            if (exit$1 === 2) {
              if (gameId === "matches") {
                var match$3 = match$1[1];
                var match$4 = match$3[1];
                var matchId = match$3[0];
                if (match$4) {
                  if (match$4[0] === "new-script" && !match$4[1]) {
                    page = React.createElement(ScriptWizard$ReactTemplate.make, {
                          matchId: matchId
                        });
                  } else {
                    exit = 1;
                  }
                } else {
                  page = React.createElement(MatchDetails$ReactTemplate.make, {
                        matchId: matchId
                      });
                }
              } else {
                exit = 1;
              }
            }
            
          } else {
            page = React.createElement(GameList$ReactTemplate.make, { });
          }
          break;
      case "new-game" : 
          if (match[1]) {
            exit = 1;
          } else {
            page = React.createElement(GameWizard$ReactTemplate.make, { });
          }
          break;
      case "profile" : 
          if (match[1]) {
            exit = 1;
          } else {
            page = React.createElement(UserProfile$ReactTemplate.make, { });
          }
          break;
      default:
        exit = 1;
    }
  } else {
    page = React.createElement(HomePage$ReactTemplate.make, { });
  }
  if (exit === 1) {
    page = React.createElement(NotFoundPage$ReactTemplate.make, { });
  }
  return React.createElement("div", undefined, React.createElement(NavigationBar$ReactTemplate.make, { }), page);
}

var make = App;

exports.make = make;
/* react Not a pure module */
