micronaut:
    application:
        name: core
    security:
        enabled: true
        oauth2:
            enabled: true
            clients:
                keycloak: 
                    client-id: 'keycloak-client'
                    openid:
                        issuer: http://localhost:8090/auth/realms/Keycloak
        intercept-url-map:
        -
            pattern: /graphiql
            access:
                - isAuthenticated()
        -
            pattern: /graphql
            access:
                - isAuthenticated()
        token:
            jwt:
                enabled: true 
                cookie:
                    enabled: true
                signatures:
                    jwks:
                        keycloak:
                            url: http://localhost:8090/auth/realms/Keycloak/protocol/openid-connect/certs
jackson:
    module-scan: false
graphql:
    graphiql:
        enabled: true
