repository: gcr.io/codattle

images:
  core:
    tag: latest
  frontend:
    tag: latest
  simulation:
    tag: latest

rabbitmq:
  rbacEnabled: false
  rabbitmq:
    username: guest
    password: guest

mongodb:
  mongodbUsername: mongo
  mongodbPassword: mongo
  mongodbDatabase: default

keycloak:
  keycloak:
    username: admin
    password: admin
    service:
      type: NodePort
    extraVolumes: |
      - name: realm-secret
        secret:
          secretName: realm-secret
    extraVolumeMounts: |
      - name: realm-secret
        mountPath: "/realm/"
        readOnly: true
    extraArgs: -Dkeycloak.import=/realm/realm.json
