// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("ScriptEditor");

function make(onChange, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              return React.createElement("textarea", {
                          value: param[/* state */1][/* text */0],
                          onChange: (function ($$event) {
                              return Curry._1(send, /* ChangeText */[$$event.target.value]);
                            })
                        });
            }),
          /* initialState */(function (param) {
              return /* record */[/* text */""];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              var text = action[0];
              return /* UpdateWithSideEffects */Block.__(2, [
                        /* record */[/* text */text],
                        (function (param) {
                            if (onChange !== undefined) {
                              return Curry._1(onChange, text);
                            } else {
                              return /* () */0;
                            }
                          })
                      ]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
