// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function ScriptEditor(Props) {
  var onChange = Props.onChange;
  var match = React.useState((function () {
          return "";
        }));
  var setScript = match[1];
  return React.createElement("textarea", {
              value: match[0],
              onChange: (function ($$event) {
                  var script = $$event.target.value;
                  Curry._1(setScript, (function (param) {
                          return script;
                        }));
                  return Belt_Option.mapWithDefault(onChange, /* () */0, (function (onChange) {
                                return Curry._1(onChange, script);
                              }));
                })
            });
}

var make = ScriptEditor;

exports.make = make;
/* react Not a pure module */
